### ISSUE TITLE
Cached mesh export

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#10]
Only re-export a mesh if it has changed.
edit: this is implemented.

**Comment by Theverat** [comment]
Maybe we can add a "save to disk" feature to DefineBlenderMesh in pyluxcoreforblender.

**Comment by Dade916** [comment]
With the introduction of Serialization, the code for saving any type of mesh is already available. I can expose this feature to save a single Mesh. Something like Scene::SaveMesh(meshName).

**Comment by Theverat** [comment]
That would be great.
I'm still thinking about some possible ways to do the caching.

One option would be to keep a single luxcore_scene alive the whole time Blender runs and only update it when a viewport or final render is started.
However I have the feeling I would open a whole can full of possible bugs with this approach.

So I think the more safe variant is to have a Scene::SaveMesh like you said and save the meshes to a temp file when the RenderEngine instance is deleted (i.e. the luxcore_session is stopped and deleted).
I only want to save to disk at the end of a session because otherwise we get a lot of write operations when someone for example sculpts a mesh while the viewport render is running.

The temp file handling would be done by a class similar to the current image cache: 
https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/image.py
And all temp meshes would be deleted when Blender is closed.

**Comment by Dade916** [comment]
You seem to work under the assumption that loading a mesh from file is faster then defining a mesh from memory. This i not true since the introduction of DefineBlenderMesh(). I'm pretty sure that the execution time of DefineBlenderMesh() is smaller than some Scene::LoadMesh().

So, I assume, the source of the problem is in some transformation of Blender mesh prior of DefineBlenderMesh() call. Like for instance, splitting the mesh according the materials used. The solution would be to link Blender mesh with multiple LuxCore meshes saved on files. In order to not just skip DefineBlenderMesh() but all the Blender mesh pre-processing phase. Is this correct ? Can you point me to the "incriminated" code ?

In this case, a possible solution would be also to accelerate all the pre-process phase in C++ (not just DefineBlenderMesh()) but it would be far more complex than a Scene::SaveMesh() and it is something I would like to avoid.

**Comment by Theverat** [comment]
> So, I assume, the source of the problem is in some transformation of Blender mesh prior of DefineBlenderMesh() call. 
Yes. The problem is the `blender_obj.to_mesh()` method.
https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/blender_object.py#L29
It is very fast when there are no modifiers on the object, but when there are modifiers, it has to evaluate all of them obviously.
And we can't really replicated this as we would have to implement all Blender modifiers. And it would probably not even be faster since blender already does this in C code.

I guess I will not even cache meshes without modifiers because of the reason you mentioned.
The loading from disk is purely there to skip the to_mesh method.

**Comment by Dade916** [comment]
Ahah, Scene::SaveMesh() is already available in LuxCore (and I assume it was used by LuxBlend).

I extended the code to so .bpy file format (i.e. serialized mesh) can be used in any place where it was possible to use only a .ply file before.
So the file extension drives the file format used to save or the one expected when loading.

**Comment by Theverat** [comment]
It was made available for this purpose, but I never came around to use it.

**Comment by Theverat** [comment]
I implemented a disk based mesh cache, but it is slower than to_mesh and DefineBlenderMesh.
So I pushed it into a branch for future reference and I don't intend to merge it into master.
https://github.com/LuxCoreRender/BlendLuxCore/tree/mesh_disk_cache
