### ISSUE TITLE
Artifacts on the background image

### ISSUE THREAD

**Issue by PavelBlend** [LuxCoreRender/BlendLuxCore#209]
#### System Information

Operating system - Windows 7 64 bit
graphics card - None

#### Software Version

* Blender version:  2.79
* LuxCore version: 2.1 alpha3

#### Short description of error
The background image (Camera > LuxCore imagepipline > Background image) has step artifacts.

#### Exact steps for others to reproduce the error
[background_image_test.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2364481/background_image_test.zip)

**Comment by Theverat** [comment]
A picture to illustrate the problem (render on the left, input image on the right):
![2018-09-09_19-49-35](https://user-images.githubusercontent.com/1584761/45267263-94740f80-b469-11e8-9cf0-dd5ae6905ecb.png)

**Comment by Theverat** [comment]
I have exposed the "storage" property of the background image.
https://github.com/LuxCoreRender/BlendLuxCore/commit/ac10b061a5cd8745834fb7716dfdb037c00e0872

When I change it from the default "byte" to "float", the banding becomes less obvious, but it's still there.
However, I consider this a problem in LuxCore (could be caused by precision loss due to gamma correction or something like that). 
So if you still have this problem, please open an issue in the LuxCore repository.
