### ISSUE TITLE
There is no "warmup samples" and "test step samples" with bidir rendering

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/BlendLuxCore#239]
If I want to use bidir+sobol/random

in the Luxcore Halt Conditions:
I don't get option to set test step and warmup samples and no blur convergence aov as well
I can only set noise threshold

**Comment by Theverat** [comment]
I could be wrong, but I think adaptive sampling doesn't really work with Bidir because it would only influence the rays fired from the camera.
While I investigated this, I stumbled upon this issue: https://github.com/LuxCoreRender/LuxCore/issues/172
Let's see what Dade says.

**Comment by Dade916** [comment]
BiDir works with adaptive sampling but, as explained by @Theverat, it has a quite marginal impact because it does affect only eye paths (you can not predict where the connection between a light path and the camera will land on the image plane).

But CONVERGENCE AOV is fully supported so there should be "warmup samples" and "test step samples" settings like with Path tracing.

**Comment by lacilaci** [comment]
Well if that's the case I'd suggest removing option for adaptivity for BiDir completely. If it has little to no impact, it will just confuse people (at least until there is better adaptivity solution)

**Comment by Dade916** [comment]
Yes, given the little effect, may be useful however halt condition based on convergence test is fully supported and legit so the missing parameters should be added.

**Comment by Theverat** [comment]
I have fixed this in 6835223bb4296d5e90dcb708fe49fe2ac4e813aa.
I also show that convergence AOV is supported by Bidir in 5853f295a52cb265ddb267a5145ecd6aae67c7ab.
