### ISSUE TITLE
override material option has no effect with viewport render

### ISSUE THREAD

**Issue by Piitas** [LuxCoreRender/BlendLuxCore#260]
#### System Information
win10, nvidia gtx 960

#### Software Version
* Blender version: 2.79b
* LuxCore version: 2.2 beta1

#### Error message from Blender console
no error message shown

#### Short description of error
override material option on the render layers tab works fine when rendering with F12 but it has no effect when doing a viewport render.

#### Exact steps for others to reproduce the error
1. Select a material as override material on the render layers tab in Blender
2. Start a viewport render  

Same effect with CPU and OpenCL

[default material bug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3170383/default.material.bug.zip)

**Comment by Theverat** [comment]
"Render layers" are a Blender concept, so I mostly try to match Cycles behaviour there, and Cycles behaves the same in this case (at least to my knowledge).

Still, it might be nice to have this as an option.
However since the whole render layer concept changed quite a bit with Blender 2.8, I will wait until the 2.8 port is done before I look into this.

**Comment by Piitas** [comment]
I had to check Cycles and indeed it does work in the same way. No worries then :)

**Comment by Theverat** [comment]
Testing in Blender 2.91, this is solved (material override now works in the viepwort, both in Cycles and BlendLuxCore).
