### ISSUE TITLE
LightGroup bug

### ISSUE THREAD

**Issue by PetrTT** [LuxCoreRender/BlendLuxCore#268]
#### System Information

Win 7  Gtx 1070

#### Software Version

* Blender version: (example: 2.79, see splash screen)
* LuxCore version: daily build 28 june 2019

Bug when light is adding to LightGroup for first time
It loose visilibility in viewport 
For render it works

**Comment by Theverat** [comment]
Do you mean you add it the the lightgroup while a viewport render is running?

**Comment by PetrTT** [comment]
Yes

**Comment by Theverat** [comment]
For future work on this problem: 
When a lightgroup is added or removed during viewport render, we need a config update (more precisely, a re-export of the imagepipline related code, which is handled in config export).
However, currently we have no way to detect an added/removed lightgroup during viewport render, and I see no obvious and simple way to add this. So I see this as a known problem that has a low priority to fix, because it's only a minor annoyance and the required code changes are probably big.

By the way, a simple workaround to get the new lightgroup to show up is to enforce a config update, for example by making the 3D viewport window slightly smaller or larger.

**Comment by Theverat** [comment]
This is no longer a problem because of the lightgroup rework in v2.5.
