### ISSUE TITLE
Bug in hair export

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#271]
Scene: [hrs.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3403076/hrs.blend.zip)

![cycles_hairs](https://user-images.githubusercontent.com/1584761/61396920-0d819600-a8c9-11e9-8d57-d5de37f93f43.jpg)

![luxhairs](https://user-images.githubusercontent.com/1584761/61396924-0f4b5980-a8c9-11e9-9237-8dcd00e6bb8b.jpg)

Reported by DEBIHOOD.

**Comment by povmaniaco** [comment]
I have encountered the same problem before. In some cases, the hair modifiers only affect the 'child' particles. You must filter and export only these particles.
`#
    parents = len(pSys.particles)
    childrens = len(pSys.child_particles)
    start = 0
    totalHairs = parents
    if childrens > 0:
        start = parents
        totalHairs = childrens
    #
    for idx in range(start, totalHairs):
        # export code...
`

[TheBounty](https://github.com/TheBounty/Core/wiki/Hair)

**Comment by Theverat** [comment]
Thanks for the help. So it's a bug (or design decision) in Blender?

**Comment by povmaniaco** [comment]
I'm not sure it's a bug. Fix the error in my exporter and I have not investigated more.

**Comment by neo2068** [comment]
Hi!
I looked into the issue and there is no bug. The problem comes from the high max error for the adaptive hair sampling in LuxCore. If you lower the value for max error or use one of the non adaptive modes, i.e. solid or triangle ribbon, it renders correctly.
![hair_settings](https://user-images.githubusercontent.com/17701407/61980411-fe9c9100-aff6-11e9-9ee9-b6689d0f9382.jpg)
![hair_luxcore](https://user-images.githubusercontent.com/17701407/61980413-ffcdbe00-aff6-11e9-9efb-877a20f3554d.png)

**Comment by Theverat** [comment]
Nice, thanks for checking!
