### ISSUE TITLE
Mac OS 2.8 test build available?

### ISSUE THREAD

**Issue by thhart** [LuxCoreRender/BlendLuxCore#292]
Any chance to have a test build for Mac? Or maybe some hints how to build? I highly appreciate.

Thanks
Thomas

**Comment by Theverat** [comment]
> Any chance to have a test build for Mac?

None of the current developers has macOS, so someone else will have to step forward.

> Or maybe some hints how to build?

Unfortunately I can't give you a step-by-step guide. The [MacOSCompile](https://github.com/LuxCoreRender/MacOSCompile) repo is empty, and I'm not sure the [MacOSCompileDeps](https://github.com/LuxCoreRender/MacOSCompileDeps) repo alone is enough to create a build.
@rebpdx was the last one who did macOS builds, maybe he can comment on this.

**Comment by rebpdx** [comment]
MacOSCompile was never needed and could be deleted since LuxCore just uses the artifacts from MacOSCompileDeps.

The biggest thing is to setup pyenv on your system like described in the [MacOSCompileDeps README](https://github.com/LuxCoreRender/MacOSCompileDeps/blob/master/README.md)

Then in MacOSCompileDeps open a terminal go to the repo parent directory and call `./cut_deps_release`

To build LuxCore you can follow the same steps on azure's [build shell file](https://github.com/LuxCoreRender/LuxCore/blob/master/scripts/azurepipeline/macos/build.sh)

And then in this repo you run the `./release/package_releases.py` however, I don't remember how to do that on a local build rather than it's usual fetch the latest version from LuxCore repo

**Comment by Theverat** [comment]
Thanks Rob!

**Comment by jamespa16** [comment]
I gave it a shot but it ended in macOS 10.15 having problems with itself. To be expected from beta OS builds I guess. @thhart are you on the LuxCore Discord? I can give some pointers about what I did, and how to get to where I was if so.

**Comment by thhart** [comment]
Joined Discord now, seen as _Thomas_

**Comment by philovivero** [comment]
https://github.com/LuxCoreRender/MacOSCompileDeps/releases

The latest thing in there is:

```
LuxCoreRender v2.1beta3
@rebpdx rebpdx released this on Nov 27, 2018
```

Is this also something I need to build to build the MacOS Blender plugin? The scripts at https://github.com/LuxCoreRender/LuxCore/blob/master/scripts/azurepipeline/macos/build.sh seem to assume they just exist to wget/curl away.

**Comment by Dade916** [comment]
It is now available here: https://forums.luxcorerender.org/viewtopic.php?f=9&t=1599#p18833
