### ISSUE TITLE
'Visible to Camera' in viewport don't work when changed with python

### ISSUE THREAD

**Issue by iszotic** [LuxCoreRender/BlendLuxCore#381]
#### System Information
Kubuntu 18.04.3 (kernel 5.0.0)
AMD Vega 56
#### Software Version
* Blender version: 2.83 (sub 3), branch: master, commit date: 2020-02-16 19:56
* LuxCore version: 2.3 beta1

#### Short description of error
'Visible to Camera' object property changes done with a python script are not reflected in viewport when rendering mode is set.
#### Exact steps for others to reproduce the error
To the default scene, add another mesh object, then select the cube and execute the following command in the python console or text editor

```
for obj in bpy.context.window.view_layer.objects:
    obj.luxcore.visible_to_camera = obj.select_get()
```

If you look at the properties panel, in the objects subpanel, the cube is visible to the camera and the other one is not, but when rendering mode is set in viewport all objects are visible to the camera, it should only show to the camera the cube. It works when the blendfile is reloaded, when the scene is rendered or when you manually check the 'Visible to Camera' checkbox

**Comment by Theverat** [comment]
I think this is somewhat a regression (or maybe by design) of the new depsgraph in Blender and doesn't have anything to do with our addon.

I think you have to manually flag the object for update, like so: `obj.update_tag()` after you change its properties. 
Afterwards, you have to force a redraw of the rendered 3D view, either by hovering it with the mouse or by using a function like this: https://github.com/LuxCoreRender/BlendLuxCore/blob/b9b8fa71848f47b14471846d6733d8f378d70078/utils/ui.py#L79

**Comment by iszotic** [comment]
Hi, thanks for the reply.
By object it works, but by scene I set this in console
`C.screen.update_tag()` #also with C.window_manager.windows[0].screen or C.window.screen
then I use this
`C.screen.areas[4].regions[5].tag_redraw()`, where area[4] is the only 'VIEW_3D' type area in the workspace and the region is a 'WINDOW' type region, also tried with all type regions
In cycles and luxcore blender doesn't do anything

**Comment by Theverat** [comment]
I meant "scene", not "screen".
