### ISSUE TITLE
Show Indirect/Path Mix in debug mode is not working

### ISSUE THREAD

**Issue by zebus3d** [LuxCoreRender/BlendLuxCore#405]
MacOS High Sierra
Nvidia Geforce GTX 780M 4096MB

Blender version: 2.81a
LuxCore version: 2.3

Apparently no error in console. 

When I try to render with Show Indirect/Path to see the image with the blue and red colors, I don't get a correct debug image. 

[test_debug.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4365204/test_debug.blend.zip)

Correct result: 
![Captura de pantalla 2020-03-22 a las 12 43 25](https://user-images.githubusercontent.com/48990185/77249354-afb80180-6c40-11ea-9107-deea8fdfed34.png)

My result:
![Captura de pantalla 2020-03-22 a las 12 38 55](https://user-images.githubusercontent.com/48990185/77249363-be9eb400-6c40-11ea-9e20-397eaa7e2491.png)

**Comment by Theverat** [comment]
The cause is a combination of these factors:
* You have "add light tracing" enabled, which will be added on top of the render.
* The tonemapping settings lead to a very dark image in debug mode (so dark that it appears almost black).

When I set tonemapper to linear with gain 1, I get this:

![untitled](https://user-images.githubusercontent.com/1584761/77253767-d6843100-6c5c-11ea-919f-63ed6b9c64dd.png)

I should fix this in the addon (force linear tonemapper with gain 1 and disable light tracing when photonGI debug is enabled).
Until that is done, you will have to do these steps manually.

**Comment by Theverat** [comment]
> I should fix this in the addon (force linear tonemapper with gain 1 and disable light tracing when photonGI debug is enabled).

I have implemented this in eb62ffd228a58a7e1a901149de6b832074970feb

**Comment by zebus3d** [comment]
@Theverat Thank you very much!

**Comment by zebus3d** [comment]
Now with the Debug Show Indirect, the image is burned out now, but with the camera tonemapper it's fine.
