### ISSUE TITLE
LOL: "key not in subgroup dict"

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#458]
.blend file: 
Default scene: [untitled.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4640843/untitled.zip)

Steps to reproduce:
* Open scene
* Toggle system console
* Make asset bar visible
* Click category "Furniture"
* Drag one of the assets into the scene
* While the asset is being downloaded, change to category "Decoration"
* The console will now be filled with errors (see below) and the green loading box will no longer show a thumbnail.

```
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlendLuxCore_git\operators\lol\assetbar.py", line 135, in draw_callback_3d_progress
    bbox_min = Vector(asset_data["bbox_min"])
KeyError: 'key not in subgroup dict'
```

OS: Windows 10
Blender version: 2.82a
LuxCore version: 98f7e1d2c2b551104e4276498c079613cd2c25c9

@neo2068

**Comment by neo2068** [comment]
That was a nasty one. The category selection creates a new instance of the assetbar operator and the old one is deleted. The result is that the reference of asset data in the downloader is not accessable anymore due to garbage collection. Coping the asset_data during downloader creation solves the issue.
