### ISSUE TITLE
Render does not start on Ryzen machine with linux

### ISSUE THREAD

**Issue by vrsebas** [LuxCoreRender/BlendLuxCore#480]
I'm using CPU for rendering with a Ryzen 5 3400g in archlinux and blender 2.83, but when I try to enter in the render preview it doesn't show and the log sends this line:
CUDA driver API error CUDA_ERROR_NOT_INITIALIZED (code: 3, file:/home/vsts/work/1/s/LinuxCompile/LuxCore/src/luxrays/core/context.cpp, line: 112): initialization error
The CPU has a vega 11 chipset which should work with OpenCL but It keeps looking for a CUDA device.

**Comment by Dade916** [comment]
It is quite strange, it is like if you had CUDA installed but without any NVIDIA GPU, is that possible ?

The error is here (https://github.com/LuxCoreRender/LuxCore/blob/e15e45ceffe7bbd31e8be78c2e37a6d8acef7c47/src/luxrays/core/context.cpp#L112) and at this point, the code has already successful initialized CUDA and even done a call to check this verison.
This should mean you have a broken CUDA installation (?).

BTW, have you compiled LuxCore on your own ?

**Comment by vrsebas** [comment]
Yes, I have installed CUDA because of blender in order to build it complete, but since I'm not using  could uninstall CUDA and try it again, and no, I didn't compiled LuxCore

**Comment by Dade916** [comment]
It looks like CUDA doesn't handle well that situation, when asked how many devices are available, it throws an error instead of 0. You have probably installed the CUDA SDK but not NVIDIA drivers and this doesn't seem to be handled well.

As work around, you should disable OpenCL image pipeline. Even if you are doing CPU-only rendering LuxCore, by default, will still try to use a GPU for the image pipeline (i.e. tone-mapping, post-processing image effects, etc.).

**Comment by vrsebas** [comment]
I see, that could be the reason, I just uninstalled CUDA and it worked fine. But that's good to know, thanks a lot!.
