### ISSUE TITLE
Unable to install on Ubuntu 16.04. ImportError version `GLIBC_2.25' not found. How to update glibc?

### ISSUE THREAD

**Issue by Shreeyak** [LuxCoreRender/BlendLuxCore#488]
I'm not able to install, getting the following error message. I've tried both OpenCL and CPU versions on Blender 2.82a and 2.83. 

```bash
Modules Installed (BlendLuxCore) from '/home/shrek/software/blender-2.83/addons_downloaded/BlendLuxCore-latest-linux64.zip' into '/home/shrek/.config/blender/2.83/scripts/addons'
Traceback (most recent call last):
  File "/home/shrek/software/blender-2.83/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/shrek/.config/blender/2.83/scripts/addons/BlendLuxCore/__init__.py", line 64, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/shrek/.config/blender/2.83/scripts/addons/BlendLuxCore/bin/pyluxcore.so)
```

I'm running Ubuntu 16.04 and have the glibc 2.23, which is less than 2.25, as the error indicates. 

```bash
$ ls -l /lib/x86_64-linux-gnu/libc.so.6
lrwxrwxrwx 1 root root 12 Feb  6  2019 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.23.so
```

Apparently, updating glibc can cause serious problems. Any tips on updating glibc to 2.25 or greater on Ubuntu 16.04?

**Comment by Dade916** [comment]
I think it would be easier to update to Ubuntu 18.04 than trying to install a newer GLIBC on an older system.

The other option could be to compile LuxCore from the source on your Ubuntu 16.04 however it can be a complex process (https://github.com/LuxCoreRender/LinuxCompile) if you are not familiar with compiling code.
I'm also not totally sure if it is possible because you could hit some other kind of incompatibility (for instance some used Intel binary library may have been compiled and linked with a newer GLIBC too).

**Comment by Shreeyak** [comment]
Thanks @Dade916 , I solved my issue by creating a Docker container running Ubuntu 18.04. 
Maybe we could add a disclaimer on the download side, about min operating sys requirement? Or by updating this error message to suggest upgrading the OS?

**Comment by Dade916** [comment]
> Maybe we could add a disclaimer on the download side, about min operating sys requirement?

It is hard to list the compatible distributions with the endless number of different Linux systems (and versions) available out there (i.e. I don't know what is compatible and what is not without just trying).
We compile the Linux binary with, as many as possible, libraries statically linked in order to try to minimize the problems.
