### ISSUE TITLE
Displacement behaviour broken

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/BlendLuxCore#563]
.blend file: 

[Displacement_bug.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5214458/Displacement_bug.blend.zip)

Steps to reproduce:
Just open the file and enable the viewport render mode, you will see how the displacement is not present just in the red parts, it should be just in the red parts, I'm using the same mask for both, materials and displacement.

Screenshots or rendered images:
![image](https://user-images.githubusercontent.com/20524718/93022280-cedc8e00-f5e8-11ea-9f16-a99887a26968.png)

Error message from Blender console:
No error message

OS: Linux Mint 19.3
Blender version: 2.83 LTS and 2.90
LuxCore version: 2.5 alpha

**Comment by Theverat** [comment]
The default mapping of procedural textures used here is _global mapping_.
If you move a surface through the 3D space taken up by the procedural texture, the 2D pattern visible on the surface will appear to morph - different parts of the texture are shown depending on the position of the mesh.
What happens here is that the procedural textures are evaluated the first time for the displacement, then the mesh is displaced, and then they are evaluated a second time during rendering - but the mesh will be in a different position than the first time because it was displaced.

The solution is to use a texture mapping that is deformed along with the displacement, which is the "UV" mapping.

![Capture](https://user-images.githubusercontent.com/1584761/93022957-1ca6c580-f5ec-11ea-9e0c-959dcd6d4022.PNG)

**Comment by juangea** [comment]
OK, awesome! 

Thanks for clarifying it :)

**Comment by juangea** [comment]
However if we have to use UV mapping, that means that we loose the procedurality of the noise, and we also get seams, which is something we don't want.

May be a current limitation, but something to take into account I think
