### ISSUE TITLE
Add appstream metadata

### ISSUE THREAD

**Issue by luyatshimbalanga** [LuxCoreRender/BlendLuxCore#567]
This file includes a metadata needed to read the BlendLuxCore as add-on for Blender on Gnome Software and Ubuntu Software for installation following [appstream guideline](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Addon.html).
The file can be located anywhere in the directory. For example,
 Blender places it inside release/freedesktops

Metadata file
[com.github.luxcorerender.blendluxcore.metainfo.xml.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/5252273/com.github.luxcorerender.blendluxcore.metainfo.xml.txt)

**Comment by Theverat** [comment]
The official way to install the addon is described here: https://wiki.luxcorerender.org/BlendLuxCore_Installation
A metadata file is not required for this. 

I am reluctant to add something like this because it will require maintenance in the future. So there needs to be a real benefit from adding it.
