### ISSUE TITLE
Add support for caustics output

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#573]

**Comment by Theverat** [comment]
@Dade916 The Output Switcher imagepipeline plugin only works with film channels, not with film outputs, so as far as I can see there is no way to run the caustics output through the imagepipeline, is that correct?
I think it would be good to make it possible to tonemap the caustics output, otherwise the user will have to manually tonemap it to match the render, and keep this process in sync if tonemapping settings change etc.

**Comment by Dade916** [comment]
It should be possible to add Caustic AOV support to the OuputSwitcher, the code will be quite different from other AOVs but it should work transparently from the outside point of view. I will check.

**Comment by Dade916** [comment]
I added the support for "CAUSTIC" AOV to OutputSwitcherPlugin.

**Comment by Theverat** [comment]
Thanks, I have done the addon code.

Two things that occured to me about the caustic AOV:
* As a user I would expect it to include _all_ caustics. Currently it does not contain caustics rendered with the PhotonGI caustic cache.
* Currently it does not contain the expected result when rendering with Bidir, since the light tracing buffer doesn't just contain caustics in that case. It might be a good idea to return a black buffer if the caustic AOV is requested in that case instead.

**Comment by Dade916** [comment]
> * As a user I would expect it to include _all_ caustics. Currently it does not contain caustics rendered with the PhotonGI caustic cache.

This is true in general for most AOVs and PhotonGI. PGI stores a single merged information so it is not possible to generate many types of AOVs (diffuse indirect light, glossy indirect light, etc.).
Storing a separate information would require a huge amount of additional memory.

It would be possible to add support for caustics from PGI because they are stored in a separate cache (caustic cache Vs indirect cache).
However I would have to use a real Caustic AOV (i.e. allocate the memory for the AOV framebuffer) instead of, like now, have a virtual one that require no additional memory.

> * Currently it does not contain the expected result when rendering with Bidir, since the light tracing buffer doesn't just contain caustics in that case. It might be a good idea to return a black buffer if the caustic AOV is requested in that case instead.

This is not possible because a film has no knowledge of how it has been created and filled (for instance can be loaded from a file, etc.). I could only add a check at RenderConfig level where I know the current render engine and the film.

**Comment by Theverat** [comment]
Ok, then we'll leave it like it is now. I have added warnings/notes about these special cases in the addon.
