### ISSUE TITLE
Single object with multiple UV maps, only first UV map gets used

### ISSUE THREAD

**Issue by kintuX** [LuxCoreRender/BlendLuxCore#586]
.blend file: 
[UV_multiples-bug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5502019/UV_multiples-bug.zip)

Steps to reproduce:
switch UV maps (doesn't work)

Screenshots or rendered images:
![UV_multiples-bug](https://user-images.githubusercontent.com/61623470/98383984-7b694800-204d-11eb-92c5-1098f6c4449d.gif)

Error message from Blender console:

OS: 
Blender version: 2.83.8 LTS
LuxCore version: 2.5 daily

**Comment by maljos** [comment]
I have the same problem

**Comment by Theverat** [comment]
Did you upload the wrong example scene? It is a .blend1, the renderer is set to eevee and it doesn't have a LuxCore material that demonstrates the issue.

A workaround to this problem is to use a 2D mapping node and select the UV layout that should be used:

![Screenshot from 2020-11-19 12-58-03](https://user-images.githubusercontent.com/1584761/99663518-080d0080-2a67-11eb-83fc-d047e1d2bc63.png)

**Comment by kintuX** [comment]
Yes, I made a mistake sending wrong & incomplete set.
Here's the correct one:
[UV_multiples-bug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5567309/UV_multiples-bug.zip)
 ... and thanks for the note :)
