### ISSUE TITLE
Smoke Domain Intersection Issue

### ISSUE THREAD

**Issue by DionXein** [LuxCoreRender/BlendLuxCore#601]
.blend file: 
https://drive.google.com/file/d/14JPsyvYiw-oIBtubgLlzy6AKlH5YcT_o/view?usp=sharing

[Volume_intersect_issue.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5608591/Volume_intersect_issue.zip)

Steps to reproduce:
Just create quick smoke, bake a few steps(in attached blend file just 20 frame so it would be easy to reproduce).
Move smoke domain to objects to see changes.

Screenshots or rendered images:
![1_No_Intersection](https://user-images.githubusercontent.com/75082591/100365760-58f99780-3019-11eb-847f-f44aac416485.jpg)
![2_With_Intersection](https://user-images.githubusercontent.com/75082591/100365774-5d25b500-3019-11eb-8567-753859269190.jpg)
![3_No_Intersection_Side](https://user-images.githubusercontent.com/75082591/100365793-60b93c00-3019-11eb-9eb9-b200ea27343a.jpg)
![4_With_Intersection_Side](https://user-images.githubusercontent.com/75082591/100365805-63b42c80-3019-11eb-8668-cffc083de520.jpg)

OS: Win10
Blender version: 2.90.1
LuxCore version: 2.5 alpha1 last build

**Comment by pot-code** [comment]
Same here.

MacOS
Blender v2.83.9
LuxCore v2.4

Node used: Heterogeneous Volume, Smoke

**Comment by Theverat** [comment]
I simplified the scene a bit, deleting superfluous objects: 
[Volume_intersect_issue2.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5643059/Volume_intersect_issue2.zip)

The problem seems to arise from the interaction of the glossytranslucent material of the sphere, the homogeneous volume inside the sphere (with priority 1) and the volume of the cube (with priority 0). In the intersecting part where volume priority comes into play, the glossytranslucent material behaves wrong.

Render with sphere and cube:

![1](https://user-images.githubusercontent.com/1584761/101170148-4e08bd80-363e-11eb-8a43-6f08ff14989a.jpg)

Render with only the sphere:
(I think this is the correct, expected output for the "sphere and cube" case)

![2](https://user-images.githubusercontent.com/1584761/101170317-91632c00-363e-11eb-93d9-fabaee6f13b6.jpg)

Render without the homogeneous volume of the sphere (so only glossytranslucent material interacting with clear volume):

![3](https://user-images.githubusercontent.com/1584761/101170489-d4250400-363e-11eb-93b5-7ec60ade7181.jpg)

**Comment by Dade916** [comment]
Explained here: https://forums.luxcorerender.org/viewtopic.php?f=4&t=2825&p=26991#p26991

I will mark this as "wontfix".

**Comment by Theverat** [comment]
@DionXein The correct solution to this problem is to set Opacity to 1 in the glossytranslucent material of the sphere, which will give the correct result:

![4](https://user-images.githubusercontent.com/1584761/101284271-6cf28580-37df-11eb-9c54-be4776439155.jpg)
