### ISSUE TITLE
Mapping node inputs / Color to normal map 

### ISSUE THREAD

**Issue by Nicknroll** [LuxCoreRender/BlendLuxCore#606]
I want to propose add inputs for mapping node, it could be helpful to avoid tiling in some cases, especially for arrayed objects. 

![mapping inputs](https://user-images.githubusercontent.com/74839903/102010815-1ccc7380-3d49-11eb-96e4-110686541af1.jpg)

Also would be nice to have not only Triplanar normal mapping node but 2d too. 

Thank you!
-Nick

**Comment by Theverat** [comment]
It is unlikely that texturable mapping will ever be implemented, because it would mean a big performance hit for all textures on GPUs.

There are alternatives though, for example the new "distort" texture in v2.5, and this feature: https://forums.luxcorerender.org/viewtopic.php?f=5&t=2533 (not yet available in the Blender addon)

> Also would be nice to have not only Triplanar normal mapping node but 2d too.

You can just enable the "normalmap" option in the image texture node to use a regular normalmap.

**Comment by Nicknroll** [comment]
Isn't this the same like if i just move manually each island in the UV editor? 

Great! I didn't know it can convert color to normal map. 
Also, is it possible to add something alike 'bump math node', to combine bump and normal maps?

**Comment by Theverat** [comment]
> Also, is it possible to add something alike 'bump math node', to combine bump and normal maps?

You can use the "add" operation of the regular math node for that. It has a special code path for adding bump/normal maps.
