### ISSUE TITLE
Preview ball mapping scale

### ISSUE THREAD

**Issue by Nicknroll** [LuxCoreRender/BlendLuxCore#607]
Since Blender has no world scale uv, many materials have to be scaled what makes preview ball a bit useless. 
Would be better if preview ignored mapping scale. 

![Screenshot_2](https://user-images.githubusercontent.com/74839903/102130168-2cd37880-3e59-11eb-8e3d-a681f6a9abf8.jpg)

Thank you!
Nick

**Comment by Theverat** [comment]
This has two problems:
- You can't just ignore all scales because it would erase any relative difference between various scaled textures in the previews. (e.g.: you have one texture scaled by 0.5, another by 2 - how should a mix of the two look in the preview?)
- It would be very confusing if the material preview would ignore certain nodes
