### ISSUE TITLE
Remap node source auto-bounds

### ISSUE THREAD

**Issue by Nicknroll** [LuxCoreRender/BlendLuxCore#614]
Hello
It could be nice if remap node had source domain auto-boundaries, cause it will allow easily get full brightness range of map.
It will be useful for creating all kind of maps (roughness, bump etc) from single diffuse map.

![Screenshot_13](https://user-images.githubusercontent.com/74839903/103567034-b95adf00-4ecb-11eb-9794-e290fab5359b.jpg)

Also, why target domain 1-0 doesn't make image negative?

Thank you!
Nick

**Comment by Theverat** [comment]
> It could be nice if remap node had source domain auto-boundaries, cause it will allow easily get full brightness range of map.
It will be useful for creating all kind of maps (roughness, bump etc) from single diffuse map.

This would only work in rare edge cases, like if the input is just a constant value or an image (in which case every pixel would need to be inspected). It won't work with general inputs since they could for example be procedural textures with unkown min/max values.

You can write a script to set the values for the edge cases I mentioned, though.

> Also, why target domain 1-0 doesn't make image negative?

Because that's not how the algorithm behind it works. Check the source code (in the LuxCore repo) for details.
