### ISSUE TITLE
Color space selection for image textures

### ISSUE THREAD

**Issue by nate-brs** [LuxCoreRender/BlendLuxCore#628]
Hi! I was wondering if it would be possible to add a color space selection menu for image texture nodes like in Cycles (see image attached)
It would be particularly useful when working with color spaces other than sRGB (ACES for example)
Thanks!

![image](https://user-images.githubusercontent.com/60856369/107510907-073ac500-6ba5-11eb-8a7f-83f2e4604d8c.png)

**Comment by Theverat** [comment]
First LuxCore would need to support color spaces other than sRGB.

**Comment by nate-brs** [comment]
Aren't color spaces independent from LuxCore?

**Comment by Theverat** [comment]
As far as I know, no.

**Comment by nate-brs** [comment]
In my (limited) experience they can be selected in the render tab independently from the render engine
![image](https://user-images.githubusercontent.com/60856369/107516021-1709d780-6bac-11eb-8686-ba41b7def765.png)

**Comment by Theverat** [comment]
LuxCore loads the image from disk (it is not transferred from Blender).

**Comment by Dade916** [comment]
It would be an image pre-processing step exactly like reverse gamma correction is now applied to texture maps. It can be done by LuxCore (like reverse gamma) or by the application.

But it is something you may don't want to do because color space reverse transformations on an 8bit image maps can lead to band issues and more.

LuxCore is agnostic: what you throw in is what you get out. So if you disable gamma correction, you can work in any color space.
