### ISSUE TITLE
ACES color space support

### ISSUE THREAD

**Issue by nate-brs** [LuxCoreRender/BlendLuxCore#630]
Hi!
The title is pretty self explanatory, would it be possible to implement the ACES color space in LuxCore?
Thanks

**Comment by idapruitt** [comment]
I use an ACES workflow with luxcore, are you still curious?

**Comment by nate-brs** [comment]
I switched to Octane but yeah, I'm still curious!
I thought ACES wasn't implemented at all in LuxCore though

**Comment by idapruitt** [comment]
What do you mean by implemented? It's possible to use ACES, you just have to be conscious of the color space of your inputs because there's no way to change them in the lux shader editor. To change the hdri color space I tell lux to use cycles settings so I can use the world editor. For image textures I usually just tweak the gamma if I don't feel like changing them from srgb to aces beforehand

**Comment by Dade916** [comment]
ACES (and OpenColorIO v2.0) support is under development and available on v2.6 branch: https://github.com/LuxCoreRender/LuxCore/commits/for_v2.6

**Comment by Dade916** [comment]
It is now available here: https://forums.luxcorerender.org/viewtopic.php?f=5&t=3446
