### ISSUE TITLE
Random UV per Mesh Island wont' work if in the node tree there is also a Random Per Island Node

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/BlendLuxCore#659]
Steps to reproduce:

- Just create a mesh with 4 islands, asign a texture and assign a 2D Mapping with Mesh Islands as seed.
- You will see proper randomization
- Now create a Random Per Island node (to randomize a color for example)
- Randomized UV per islan stops working

Screenshots or rendered images:

Without the Random ID Node:

![image](https://user-images.githubusercontent.com/20524718/113311102-3b12ab00-9309-11eb-9b85-9dad607aa5db.png)

With the Random ID Node (no need to connect it, just to create it):

![image](https://user-images.githubusercontent.com/20524718/113311147-45cd4000-9309-11eb-9b6d-799301da388a.png)

Error message from Blender console:

OS: Windows 10
Blender version: 2.92
LuxCore version: Latest RC

**Comment by Theverat** [comment]
I can reproduce it.

I changed some things that should fix it, but unfortunately it doesn't work, and I don't understand why.

**Comment by juangea** [comment]
Is great that you changed some things that should fix it... it's sad that it does not work XD

May be something in LuxCore itself @Dade916 ?

**Comment by Dade916** [comment]
But is it a BlendLuxCore problem or a LuxCore problem ?

**Comment by Theverat** [comment]
Not sure if it's a bug in LuxCore or if I just use the shapes wrong.

I'm defining shapes like the following:
```
scene.shapes.island_aov.type = "islandaov"
scene.shapes.island_aov.source = "input_mesh_shape"
scene.shapes.island_aov.dataindex = 0

scene.shapes.random_tri_aov.type = "randomtriangleaov"
scene.shapes.random_tri_aov.source = "island_aov"
scene.shapes.random_tri_aov.srcdataindex = 0
scene.shapes.random_tri_aov.dstdataindex = 1
```

As far as I know, the resulting "random_tri_aov" shape should now have two valid data indices: 
* the island ID as an integer at data index 0
* the island ID converted to a float in range 0 to 1 at data index 1

I am then accessing this data like so:

* random UV (needs integer ID):
```
<prefix>.mapping.seed.type = "triangle_aov"
<prefix>.mapping.triangleaov.index = 0
```
* random per island (needs float in range 0 to 1):
```
scene.textures.<name>.type = "hitpointtriangleaov"
scene.textures.<name>.dataindex = 1
```

The problem is that the UV is not randomized, which might indicate that the data channel 0 does not exist for some reason?
The random float data channel exists and works.

**Comment by Dade916** [comment]
I need a test scene to debug the problem.

**Comment by juangea** [comment]
Here you go :)

This is what you will see:

![image](https://user-images.githubusercontent.com/20524718/113578431-1b3df880-9623-11eb-97d2-ea21e36b887a.png)

Left object has the random UV per Island correctly working (there is no Random ID node)

The Right one, exact same material but with a Random per Island node, not connected at all, but the Random UV is not working.

Here is the file:

[bug_example.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/6258338/bug_example.zip)

**Comment by Dade916** [comment]
I have some serious problem to run Blender with my compiled LuxCore after upgrading my Linux to Ubuntu 20.04 because of different Python versions.

Anyway, @Theverat, if you export the scene with the FILESAVER, you will see that the 4 cubes on the left have the triangle AOV **#0** set, mesh-00002.ply header is:

```
ply
format binary_little_endian 1.0
comment Created by LuxRays v2.5rc1
element vertex 96
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float s
property float t
element face 48
property list uchar uint vertex_indices
element faceaov 48
property float triaov
end_header
```

Notice the "element faceaov 48" ("faceaov" means AOV 0).

while the 4 cubes on the right have the triangle AOV **1** set, mesh-00004.ply header is:

```
ply
format binary_little_endian 1.0
comment Created by LuxRays v2.5rc1
element vertex 96
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float s
property float t
element face 48
property list uchar uint vertex_indices
element faceaov1 48
property float triaov
end_header
```

Notice the "element faceaov 48" ("faceaov1" means AOV 1). However the index used is still the 0:

```
scene.textures.139788922002952Color.mapping.seed.type = "triangle_aov"
scene.textures.139788922002952Color.mapping.triangleaov.index = 0
```

I assume BlendLuxCore is setting the wrong ".mapping.triangleaov.index" to use.

**Comment by Theverat** [comment]
Here's a testscene: [cubes.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/6277902/cubes.zip)

Shape definitions:
```
scene.shapes.cubes.type = mesh
scene.shapes.cubes.ply = scenes/islandaovshape/4cubes.ply

scene.shapes.island_aov.type = "islandaov"
scene.shapes.island_aov.source = "cubes"
scene.shapes.island_aov.dataindex = 0

scene.shapes.random_tri_aov.type = "randomtriangleaov"
scene.shapes.random_tri_aov.source = "island_aov"
scene.shapes.random_tri_aov.srcdataindex = 0
scene.shapes.random_tri_aov.dstdataindex = 1
```
I would expect that the "random_tri_aov" shape now contains the mesh and two triangle AOVs:
* The islandaov result at dataindex 0
* The randomtriangleaov result at dataindex 1

However, it seems that dataindex 0 is erased somewhere in the process.

Wrong output, which I get:

![wrong_output](https://user-images.githubusercontent.com/1584761/114012378-89bec880-9866-11eb-9dc6-9751f7008cd6.png)

Expected output:
(obtained by removing the random_tri_aov shape and using the island_aov shape in the cubes object definition)

![expected_output](https://user-images.githubusercontent.com/1584761/114012352-83305100-9866-11eb-820a-543166721a47.png)

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Confirmed, thanks.

**Comment by juangea** [comment]
Awesome, will test it ASAP :)
