### ISSUE TITLE
Only export smoke texture when domain object is not hidden

### ISSUE THREAD

**Issue by neo2068** [LuxCoreRender/BlendLuxCore#67]
Smoke data is exported although the domain object is hidden or not selected for rendering.

During viewport rendering the smoke data should be exported only if the domain is visible, i.e. `domain.hide = False`.
During viewport rendering the smoke data should be exported only if the domain is visible, i.e. `domain.hide_render = False`. 

How do we distinguish if we are in viewport render or final render in texture node export?

**Comment by Theverat** [comment]
We do not check if objects are hidden/visible in texture export.
We assume that the texture export code is only called when a visible object is using the texture in a material.

I can't reproduce the problem here, can you post a test scene?
Make sure that you did not assign the smoke material/volume to any other objects in the scene other than the domain object which you are hiding.

**Comment by neo2068** [comment]
Ok, in my test file I assigned the smoke volume to all objects inside the domain as exterior volume. This comes from the old days before the volume precedence system. So, I think it is not needed anymore. After removing that, export is correct.
