### ISSUE TITLE
Discrepancy in motion blur

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/BlendLuxCore#73]

**Comment by Sharlybg** [comment]
cycles vs luxcore.
![luxcore motion blur](https://user-images.githubusercontent.com/35496087/36155927-9610ed94-10cd-11e8-81f5-c351f1633c70.jpg)
![cycles motion blur](https://user-images.githubusercontent.com/35496087/36155929-9635c182-10cd-11e8-90d0-883680bf3338.jpg)

**Comment by Sharlybg** [comment]
blend file ziped

[mustang fire1.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1720317/mustang.fire1.zip)

**Comment by Theverat** [comment]
Are you sure this isn't a bug in Cycles?
This patch to Cycles was just recently added: https://developer.blender.org/rBdb333d9ea488

You could test your file with a build from [the buildbot](https://builder.blender.org/download/), I think you need the 2.8 branch to have this commit.

**Comment by Theverat** [comment]
I just tested your file with Blender 2.79b and I get these results:

**Cycles:**
![mustang_fire_cycles](https://user-images.githubusercontent.com/1584761/38177472-8ac13480-3602-11e8-9a62-4abf89651e25.jpg)

**LuxCore:**
![mustang_fire_luxcore](https://user-images.githubusercontent.com/1584761/38177475-985f6a3a-3602-11e8-945c-e32a27dbf24d.jpg)

Maybe the problem was fixed somewhere along the way?
Not sure about the differences in the reflections, but it is probably something material related (the Cycles material does not take fresnel into account, for example).
