### ISSUE TITLE
Does the viewport and final render have different settings? 

### ISSUE THREAD

**Issue by KrytiN** [LuxCoreRender/BlendLuxCore#734]
I'm trying to render some glass and in the final render there are these circle spots of light that I don't see in the preview. Would anyone be able to explain to me what is happening and how I could change this?
<img width="628" alt="Screenshot 2021-11-01 181604" src="https://user-images.githubusercontent.com/93459050/139749516-75ed8ad3-57ee-4bf6-9f39-70730fe9c63a.png">
![image](https://user-images.githubusercontent.com/93459050/139749541-7cb37007-e609-4e5b-bd99-78e0e68993ab.png)

**Comment by Dade916** [comment]
Yes, among other things, caches are disabled in viewport rendering. You have probably caustic cache enabled.

**Comment by KrytiN** [comment]
That solved the issue! Thank you so much!

**Comment by KrytiN** [comment]
Reopening this because I would like to ask what would I have to enable/disable if I want the viewport and the final render to look the exact same so I don't have to keep flipping back and forth between the two?

**Comment by Dade916** [comment]
Under "Viewport Render" render pannel, you have some option however I don't think you can use the no-RT (i.e. no real-time) render engines  in BlendLuxCore viewport rendering.

RT render engines just produce the same results of no-RT (i.e. final render) engines aside from:

- caches
- default max. path depths

This is intended otherwise the time of view port updates could requires minutes instead of milliseconds.
