### ISSUE TITLE
Blender 3.4.1 OpenCL API error - MacOS Ventura 13.2.1

### ISSUE THREAD

**Issue by jeanmartin13** [LuxCoreRender/BlendLuxCore#816]
Hello,

I can't run BlendLuxCore 2.6.1, I have a "OpenCL API error "
![Capture d’écran 2023-02-26 à 18 34 32](https://user-images.githubusercontent.com/93234385/221426715-7bd5a179-1d38-4cd5-8fb4-45187c03f365.png)

**Comment by MigCurto** [comment]
You don't give many details, like: are you trying to upgrade a previous "latest build"?

I'm yet to install Ventura but for Monterey and before one when upgrading most of the times need to delete previous ocl_kernel_cache folder in home folder /its a hidden folder):
![Screenshot 2023-03-02 at 18 53 01](https://user-images.githubusercontent.com/14836041/222525010-6cd4fbe8-9de5-4036-a53a-f42dbd9c504a.jpg)

The reason is every single one of the last alpha builds
 have the same name and for some reason it doesn't get over written.

It will trigger a OCL kernel recompilation when using GPU.

**Comment by odil24** [comment]
Same:
https://github.com/LuxCoreRender/BlendLuxCore/issues/827
