### ISSUE TITLE
Can't get it to work. 

### ISSUE THREAD

**Issue by Vidyut** [LuxCoreRender/BlendLuxCore#828]
Sets the GPU automatically, and even if I choose CPU, says GPU API is OpenCL in preferences, but if I try to render, it won't work.

No image is rendered and I see: BVHKernel OpenCL program compilation error.

Latest blender, latest plugin. AMD CPU with integrated graphics. 16GB RAM. Ubuntu 22.04. Same result whether I use cycles materials or luxcore.

**Comment by Vidyut** [comment]
Never mind. Figured it out. uninstalled, restarted blender, switched cycles to CPU, restarted blender, installed again, and never chose GPU again. Works on CPU. Slowly, but works. Can't get the integrated GPU to work. Cycles and prorender use GPU compute, but this one won't.

**Comment by odil24** [comment]
It is normal behavior. Because not Cycles and not ProRender didn't render
as GPU of their integrated graphics card. For example, in Cycles you can
maybe select GPU compute but it will just select but not rendering with GPU
only CPU rendering works on your system.

вс, 28 мая 2023 г., 19:19 Vidyut ***@***.***>:
