### ISSUE TITLE
V2.7 beta1 for Mac doesnt have Luxcore binaries updated?Link for modified working version.

### ISSUE THREAD

**Issue by MigCurto** [LuxCoreRender/BlendLuxCore#845]
The Lastest BlendLuxCore available for Mac download isn't working (V2.7 beta1):

![Screenshot 2023-07-30 at 16 54 36](https://github.com/LuxCoreRender/BlendLuxCore/assets/14836041/46a15a1f-47d3-4b49-acdb-bc0c7e3a234b)

and someone (Alex) suggested in Discord channel to replace the bin folder of available download from the one from LuxCore: https://github.com/LuxCoreRender/LuxCore/releases/tag/luxcorerender_v2.7beta1

And that leaves you with a working version for 3.6.x

Although compiled kernels still show as 2.6 AFAIK without extensive testing is working alright:

![Screenshot 2023-07-30 at 16 36 55](https://github.com/LuxCoreRender/BlendLuxCore/assets/14836041/1cd15eaf-4f95-4da2-9666-5bc8c068b835)

So, in case anyone is looking for a working version for Blender 3.6.x Mac here's a link to modified BlendLuxCore:

https://drive.google.com/file/d/1zb1V3jJlcMHun0IgStqpSne03Jfnnhvt/view?usp=sharing

And also a link to previous one working for Blender 3.3 to 3.5 Mac (I believe you cant have them both installed at same time):

https://drive.google.com/file/d/1p3sblvHZ9GCioWZRbAobepgXiGMjTdPf/view?usp=drive_link

**Comment by alxmhn** [comment]
the problem seems to be that the version of luxcore included in the mac build was compiled prior to the commits ([1](https://github.com/LuxCoreRender/LuxCore/commit/b6a73555d89b74839759c7fca72fedec531f2956), [2](https://github.com/LuxCoreRender/LuxCore/commit/2f35684a04d9e1bd48d6ffa88b19a88871e90942)) that added support for blender 3.6.
<img width="406" alt="Screenshot 2023-07-30 at 1 39 12 PM" src="https://github.com/LuxCoreRender/BlendLuxCore/assets/127183868/4abd1569-cc43-4cf0-b5c9-ffe4b0bfda0b">

**Comment by odil24** [comment]
Thanks for clarification. We will wait @Dade916 and @neo2068 feedbacks.

**Comment by odil24** [comment]
I should close as it is not responded!
