### ISSUE TITLE
Random missing of linked object 

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/BlendLuxCore#95]
#### System Information

windows 10

#### Software Version

* Blender version: 2.79a
* LuxCore version: alpha v6
#### Error message from Blender console
the lamp is linked from another file. everytime I opened it and render, I got a different result.
some error info:
`[Duplicator "ceilingLamp"] Reference to an undefined NamedObject name: Lamp_Point__001_1434215153000`
![5](https://user-images.githubusercontent.com/8104251/37240337-df236cca-2499-11e8-9e23-69601132938a.jpg)
![1](https://user-images.githubusercontent.com/8104251/37240338-df5a4f60-2499-11e8-84db-27bdb4198a57.jpg)
![2](https://user-images.githubusercontent.com/8104251/37240339-df8f5c28-2499-11e8-8213-ae8cdb11b876.jpg)
![3](https://user-images.githubusercontent.com/8104251/37240340-dfc62c44-2499-11e8-86bc-d301826b1084.jpg)
![4](https://user-images.githubusercontent.com/8104251/37240341-dffe388c-2499-11e8-90d7-20af993131c5.jpg)

**Comment by Theverat** [comment]
Can you provide the scene (or a link to it)?

**Comment by frankyifei** [comment]
I can send it to you via email

**Comment by frankyifei** [comment]
I put it up as a repository ,link https://github.com/frankyifei/scene

**Comment by Theverat** [comment]
I should have fixed it, it was caused by the pointlights in the lamps (lights could not be used as particles, now they can).

By the way, the many triangles of the lampshades are destroying rendering performance. 
I would suggest to use matte translucent material instead, after all the lampshades themselves are not glowing in the real world either, they are just letting the light from inside through.

![untitled](https://user-images.githubusercontent.com/1584761/37545103-cbaf3fb6-2967-11e8-84c1-ee2c797cb2a9.jpg)
